// <auto-generated />
using System;
using FinalAspNetProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalAspNetProj.Migrations
{
    [DbContext(typeof(AspnetfpDbContext))]
    [Migration("20251106134205_UpdateAnalysisPrecision")]
    partial class UpdateAnalysisPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalAspNetProj.Models.DownloadableFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FileId")
                        .HasName("PK__Download__6F0F98BF04137FF4");

                    b.ToTable("DownloadableFile", (string)null);
                });

            modelBuilder.Entity("FinalAspNetProj.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("MaxRating")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyQuestionQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyTemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("SurveyQuestionQuestionId");

                    b.HasIndex("SurveyTemplateID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyId"));

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SurveyId")
                        .HasName("PK__Survey__A5481F7D1DE96033");

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyAnalysis", b =>
                {
                    b.Property<int>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisId"));

                    b.Property<decimal>("FlawProbability")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("PercentageScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ReUseProbability")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("AnalysisId")
                        .HasName("PK__SurveyAn__5B789DC82519D4ED");

                    b.HasIndex(new[] { "SurveyId" }, "UQ__SurveyAn__A5481F7C82E76A2A")
                        .IsUnique();

                    b.ToTable("SurveyAnalysis", (string)null);
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("MaxRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestionId")
                        .HasName("PK__SurveyQu__0DC06FAC7587ABD8");

                    b.ToTable("SurveyQuestion", (string)null);
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId")
                        .HasName("PK__SurveyRe__1AAA646C25AEEA33");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyResponse", (string)null);
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyTemplate", b =>
                {
                    b.Property<int>("SurveyTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyTemplateID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyTemplateID");

                    b.ToTable("SurveyTemplates");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.Question", b =>
                {
                    b.HasOne("FinalAspNetProj.Models.SurveyQuestion", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyQuestionQuestionId");

                    b.HasOne("FinalAspNetProj.Models.SurveyTemplate", "SurveyTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyTemplate");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyAnalysis", b =>
                {
                    b.HasOne("FinalAspNetProj.Models.Survey", "Survey")
                        .WithOne("SurveyAnalysis")
                        .HasForeignKey("FinalAspNetProj.Models.SurveyAnalysis", "SurveyId")
                        .IsRequired()
                        .HasConstraintName("FK_SurveyAnalysis_Survey");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyResponse", b =>
                {
                    b.HasOne("FinalAspNetProj.Models.SurveyQuestion", "Question")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_SurveyResponse_Question");

                    b.HasOne("FinalAspNetProj.Models.Survey", "Survey")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("SurveyId")
                        .IsRequired()
                        .HasConstraintName("FK_SurveyResponse_Survey");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.Survey", b =>
                {
                    b.Navigation("SurveyAnalysis");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyQuestion", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("FinalAspNetProj.Models.SurveyTemplate", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
